name: Update contributors

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0 8 15 * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-contributors:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out mainsail-docs repo
        uses: actions/checkout@v2
            
      - name: Download contributors list and commit
        run: |       
          cd ${GITHUB_WORKSPACE}/_data
          wget -O contributors.json https://api.github.com/repositories/240875926/contributors?anon=0
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          if [[ -n $(git status -s) ]]; then 
            git add .
            git commit -m "updated contributors information"
            git push
          fi
